
package org.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HashCoderService", targetNamespace = "http://Service.webService.org/", wsdlLocation = "http://localhost:8080/Service/hello?wsdl")
public class HashCoderService
    extends Service
{

    private final static URL HASHCODERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HASHCODERSERVICE_EXCEPTION;
    private final static QName HASHCODERSERVICE_QNAME = new QName("http://Service.webService.org/", "HashCoderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Service/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HASHCODERSERVICE_WSDL_LOCATION = url;
        HASHCODERSERVICE_EXCEPTION = e;
    }

    public HashCoderService() {
        super(__getWsdlLocation(), HASHCODERSERVICE_QNAME);
    }

    public HashCoderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HASHCODERSERVICE_QNAME, features);
    }

    public HashCoderService(URL wsdlLocation) {
        super(wsdlLocation, HASHCODERSERVICE_QNAME);
    }

    public HashCoderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HASHCODERSERVICE_QNAME, features);
    }

    public HashCoderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HashCoderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HashCoder
     */
    @WebEndpoint(name = "HashCoderPort")
    public HashCoder getHashCoderPort() {
        return super.getPort(new QName("http://Service.webService.org/", "HashCoderPort"), HashCoder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HashCoder
     */
    @WebEndpoint(name = "HashCoderPort")
    public HashCoder getHashCoderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.webService.org/", "HashCoderPort"), HashCoder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HASHCODERSERVICE_EXCEPTION!= null) {
            throw HASHCODERSERVICE_EXCEPTION;
        }
        return HASHCODERSERVICE_WSDL_LOCATION;
    }

}
