
package org.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HashCoder", targetNamespace = "http://Service.webService.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HashCoder {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getHashCode")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHashCode", targetNamespace = "http://Service.webService.org/", className = "org.webservice.service.GetHashCode")
    @ResponseWrapper(localName = "getHashCodeResponse", targetNamespace = "http://Service.webService.org/", className = "org.webservice.service.GetHashCodeResponse")
    public String getHashCode(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

}
